/**
 * 물리학II subject index
 * 
 * This file is auto-generated by the build script.
 * DO NOT EDIT MANUALLY.
 * 
 * Generated: 2025-04-14T03:02:35.892Z
 */
(function() {
  const subject = "물리학II";
  const assignments = [
  "[4.11] 물리 수행평가.js"
];
  
  assignments.forEach(filename => {
    const script = document.createElement('script');
    script.src = `scripts/assignments/물리학II/${filename}`;
    document.head.appendChild(script);
  });
})();