/**
 * 물리II subject index
 * 
 * This file is auto-generated by the build script.
 * DO NOT EDIT MANUALLY.
 * 
 * Generated: 2025-04-05T14:08:45.503Z
 */
(function() {
  const subject = "물리II";
  const assignments = [];
  
  assignments.forEach(filename => {
    const script = document.createElement('script');
    script.src = `scripts/assignments/물리II/${filename}`;
    document.head.appendChild(script);
  });
})();