/**
 * 화학II subject index
 * 
 * This file is auto-generated by the build script.
 * DO NOT EDIT MANUALLY.
 * 
 * Generated: 2025-05-09T12:41:33.386Z
 */
(function() {
  const subject = "화학II";
  const assignments = [
  "[5.11] 화학II 진로 연계 화학원리 PPT.js"
];
  
  assignments.forEach(filename => {
    const script = document.createElement('script');
    script.src = `scripts/assignments/화학II/${filename}`;
    document.head.appendChild(script);
  });
})();