/**
 * 화학II subject index
 * 
 * This file is auto-generated by the build script.
 * DO NOT EDIT MANUALLY.
 * 
 * Generated: 2025-04-07T03:12:50.048Z
 */
(function() {
  const subject = "화학II";
  const assignments = [];
  
  assignments.forEach(filename => {
    const script = document.createElement('script');
    script.src = `scripts/assignments/화학II/${filename}`;
    document.head.appendChild(script);
  });
})();