/**
 * 고급물리 subject index
 * 
 * This file is auto-generated by the build script.
 * DO NOT EDIT MANUALLY.
 * 
 * Generated: 2025-04-05T14:05:34.165Z
 */
(function() {
  const subject = "고급물리";
  const assignments = [];
  
  assignments.forEach(filename => {
    const script = document.createElement('script');
    script.src = `scripts/assignments/고급물리/${filename}`;
    document.head.appendChild(script);
  });
})();