/**
 * 고급물리 subject index
 * 
 * This file is auto-generated by the build script.
 * DO NOT EDIT MANUALLY.
 * 
 * Generated: 2025-05-21T09:13:56.382Z
 */
(function() {
  const subject = "고급물리";
  const assignments = [
  "[4.6] 고급물리 수행평가.js",
  "[6.13] 고급물리 주제탐구보고서.js"
];
  
  assignments.forEach(filename => {
    const script = document.createElement('script');
    script.src = `scripts/assignments/고급물리/${filename}`;
    document.head.appendChild(script);
  });
})();