/**
 * 화법과작문 subject index
 * 
 * This file is auto-generated by the build script.
 * DO NOT EDIT MANUALLY.
 * 
 * Generated: 2025-04-05T14:07:41.389Z
 */
(function() {
  const subject = "화법과작문";
  const assignments = [];
  
  assignments.forEach(filename => {
    const script = document.createElement('script');
    script.src = `scripts/assignments/화법과작문/${filename}`;
    document.head.appendChild(script);
  });
})();