/**
 * 화법과작문 subject index
 * 
 * This file is auto-generated by the build script.
 * DO NOT EDIT MANUALLY.
 * 
 * Generated: 2025-04-11T07:37:29.040Z
 */
(function() {
  const subject = "화법과작문";
  const assignments = [
  "[4.28] 화법과작문 중간고사.js"
];
  
  assignments.forEach(filename => {
    const script = document.createElement('script');
    script.src = `scripts/assignments/화법과작문/${filename}`;
    document.head.appendChild(script);
  });
})();