/**
 * 영어B subject index
 * 
 * This file is auto-generated by the build script.
 * DO NOT EDIT MANUALLY.
 * 
 * Generated: 2025-05-12T03:18:06.754Z
 */
(function() {
  const subject = "영어B";
  const assignments = [];
  
  assignments.forEach(filename => {
    const script = document.createElement('script');
    script.src = `scripts/assignments/영어B/${filename}`;
    document.head.appendChild(script);
  });
})();