/**
 * 미적분 subject index
 * 
 * This file is auto-generated by the build script.
 * DO NOT EDIT MANUALLY.
 * 
 * Generated: 2025-04-05T15:17:44.907Z
 */
(function() {
  const subject = "미적분";
  const assignments = [];
  
  assignments.forEach(filename => {
    const script = document.createElement('script');
    script.src = `scripts/assignments/미적분/${filename}`;
    document.head.appendChild(script);
  });
})();