/**
 * 미적분 subject index
 * 
 * This file is auto-generated by the build script.
 * DO NOT EDIT MANUALLY.
 * 
 * Generated: 2025-05-21T09:13:56.391Z
 */
(function() {
  const subject = "미적분";
  const assignments = [
  "[4.29] 미적분 중간고사.js",
  "[5.30] 미적분 - 그래프 그리기 수행평가.js",
  "[7.11] 미적분 수치해석 프로그래밍.js"
];
  
  assignments.forEach(filename => {
    const script = document.createElement('script');
    script.src = `scripts/assignments/미적분/${filename}`;
    document.head.appendChild(script);
  });
})();