/**
 * 미적분 subject index
 * 
 * This file is auto-generated by the build script.
 * DO NOT EDIT MANUALLY.
 * 
 * Generated: 2025-04-11T04:59:05.065Z
 */
(function() {
  const subject = "미적분";
  const assignments = [
  "[4.29] 미적분 중간고사.js"
];
  
  assignments.forEach(filename => {
    const script = document.createElement('script');
    script.src = `scripts/assignments/미적분/${filename}`;
    document.head.appendChild(script);
  });
})();