/**
 * 체육 subject index
 * 
 * This file is auto-generated by the build script.
 * DO NOT EDIT MANUALLY.
 * 
 * Generated: 2025-04-05T15:37:28.178Z
 */
(function() {
  const subject = "체육";
  const assignments = [];
  
  assignments.forEach(filename => {
    const script = document.createElement('script');
    script.src = `scripts/assignments/체육/${filename}`;
    document.head.appendChild(script);
  });
})();