/**
 * 영어독해 subject index
 * 
 * This file is auto-generated by the build script.
 * DO NOT EDIT MANUALLY.
 * 
 * Generated: 2025-04-05T14:11:54.557Z
 */
(function() {
  const subject = "영어독해";
  const assignments = [];
  
  assignments.forEach(filename => {
    const script = document.createElement('script');
    script.src = `scripts/assignments/영어독해/${filename}`;
    document.head.appendChild(script);
  });
})();