/**
 * 음악 subject index
 * 
 * This file is auto-generated by the build script.
 * DO NOT EDIT MANUALLY.
 * 
 * Generated: 2025-04-05T14:05:34.183Z
 */
(function() {
  const subject = "음악";
  const assignments = [];
  
  assignments.forEach(filename => {
    const script = document.createElement('script');
    script.src = `scripts/assignments/음악/${filename}`;
    document.head.appendChild(script);
  });
})();