/**
 * 영어A subject index
 * 
 * This file is auto-generated by the build script.
 * DO NOT EDIT MANUALLY.
 * 
 * Generated: 2025-05-09T12:46:50.478Z
 */
(function() {
  const subject = "영어A";
  const assignments = [];
  
  assignments.forEach(filename => {
    const script = document.createElement('script');
    script.src = `scripts/assignments/영어A/${filename}`;
    document.head.appendChild(script);
  });
})();