/**
 * 여행지리 subject index
 * 
 * This file is auto-generated by the build script.
 * DO NOT EDIT MANUALLY.
 * 
 * Generated: 2025-06-09T03:02:54.545Z
 */
(function() {
  const subject = "여행지리";
  const assignments = [
  "[4.13] 여행지리 음식점&보험.js",
  "[4.20] 여행지리 수행평가.js",
  "[4.6] 여행지리 숙소.js",
  "[5.18]여행지리_지형영상_1주차.js",
  "[5.25]여행지리_지형영상_2주차.js",
  "[6.1]여행지리_지형영상_3주차.js",
  "여지 - 독서활동 1차 (6.15).js",
  "여지 - 독서활동 2차 (6.22).js",
  "여지 - 독서활동 3차 (6.29).js"
];
  
  assignments.forEach(filename => {
    const script = document.createElement('script');
    script.src = `scripts/assignments/여행지리/${filename}`;
    document.head.appendChild(script);
  });
})();