/**
 * 여행지리 subject index
 * 
 * This file is auto-generated by the build script.
 * DO NOT EDIT MANUALLY.
 * 
 * Generated: 2025-04-05T15:37:14.354Z
 */
(function() {
  const subject = "여행지리";
  const assignments = [
  "[4.6] 여행지리 숙소.js"
];
  
  assignments.forEach(filename => {
    const script = document.createElement('script');
    script.src = `scripts/assignments/여행지리/${filename}`;
    document.head.appendChild(script);
  });
})();