/**
 * 지구과학II subject index
 * 
 * This file is auto-generated by the build script.
 * DO NOT EDIT MANUALLY.
 * 
 * Generated: 2025-04-05T14:05:34.185Z
 */
(function() {
  const subject = "지구과학II";
  const assignments = [
  "지구과학1.js"
];
  
  assignments.forEach(filename => {
    const script = document.createElement('script');
    script.src = `scripts/assignments/지구과학II/${filename}`;
    document.head.appendChild(script);
  });
})();