/**
 * 진로 subject index
 * 
 * This file is auto-generated by the build script.
 * DO NOT EDIT MANUALLY.
 * 
 * Generated: 2025-05-21T09:03:25.611Z
 */
(function() {
  const subject = "진로";
  const assignments = [];
  
  assignments.forEach(filename => {
    const script = document.createElement('script');
    script.src = `scripts/assignments/진로/${filename}`;
    document.head.appendChild(script);
  });
})();