/**
 * List of all subjects
 * 
 * This file is auto-generated by the build script.
 * DO NOT EDIT MANUALLY.
 * 
 * Generated: 2025-04-14T03:05:47.248Z
 */
window.SUBJECTS = [
  "고급물리",
  "기하",
  "데이터과학",
  "물리학II",
  "미술",
  "미적분",
  "여행지리",
  "영어A",
  "영어B",
  "영어독해",
  "음악",
  "지구과학II",
  "진로",
  "체육",
  "화법과작문",
  "화학II"
];