/**
 * 기하 subject index
 * 
 * This file is auto-generated by the build script.
 * DO NOT EDIT MANUALLY.
 * 
 * Generated: 2025-05-21T09:03:25.596Z
 */
(function() {
  const subject = "기하";
  const assignments = [];
  
  assignments.forEach(filename => {
    const script = document.createElement('script');
    script.src = `scripts/assignments/기하/${filename}`;
    document.head.appendChild(script);
  });
})();