/**
 * 데이터과학 subject index
 * 
 * This file is auto-generated by the build script.
 * DO NOT EDIT MANUALLY.
 * 
 * Generated: 2025-04-14T03:05:47.253Z
 */
(function() {
  const subject = "데이터과학";
  const assignments = [];
  
  assignments.forEach(filename => {
    const script = document.createElement('script');
    script.src = `scripts/assignments/데이터과학/${filename}`;
    document.head.appendChild(script);
  });
})();