/**
 * 미술 subject index
 * 
 * This file is auto-generated by the build script.
 * DO NOT EDIT MANUALLY.
 * 
 * Generated: 2025-04-11T04:59:05.064Z
 */
(function() {
  const subject = "미술";
  const assignments = [];
  
  assignments.forEach(filename => {
    const script = document.createElement('script');
    script.src = `scripts/assignments/미술/${filename}`;
    document.head.appendChild(script);
  });
})();